### ISSUE TITLE
Some commands can hang for very long periods before failing; please consider adding timeout

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#104] opened 2020-02-27 11:42 UTC
Certain commands, like "cephadm bootstrap" and `podman pull` can conceivably get stuck and hang for long periods of time, or even "forever". 

It's worth considering to precede these commands with `timeout`.

This is not just for interactive users sitting at a console - the primary purpose is to ensure that CI jobs fail within a reasonable amount of time when commands get stuck.

**Comment by sebastian-philipp** [comment] 2020-02-27 11:47
how long is too long? what about deployments with a slow download connection?

**Comment by smithfarm** [comment] 2020-02-27 11:52
> how long is too long? what about deployments with a slow download connection?

The timeout could be configurable, and default to a large number, like one hour.

**Comment by sebastian-philipp** [comment] 2020-02-28 10:41
Maybe we can improve this, if we separate the pull from calling bootstrap?

**Comment by bk201** [comment] 2020-03-02 03:57
> Maybe we can improve this, if we separate the pull from calling bootstrap?

We already did that. Images are pulled before bootstrap.

**Comment by smithfarm** [comment] 2020-03-02 17:18
Normally the `cephadm bootstrap` step completes within 5 minutes for me. But occasionally it just hangs. It just happened again today.

**Comment by sebastian-philipp** [comment] 2020-03-12 10:07
we need to fix the underlying cause of this. Please have a look at where `cephadm` actually hangs.

**Comment by smithfarm** [comment] 2020-03-12 10:25
> we need to fix the underlying cause of this. Please have a look at where `cephadm` actually hangs.

Indeed. Yesterday I found out that `cephadm bootstrap` logs to `/var/log/ceph/cephadm.log` :-)

**Comment by sebastian-philipp** [comment] 2020-09-09 08:51
can we close this?

**Comment by ricardoasmarques** [comment] 2020-09-23 20:45
I was not able to reproduce this issue.

One situation where `ceph-salt` commands will hang is when ceph cluster is stoped, and that situation is tracked on a separate issue: https://github.com/ceph/ceph-salt/issues/409

If there's any other situation where a timeout is still mission feel free to reopen or submit a separate issue for that.

**Closed as completed by ricardoasmarques** 2020-09-23 20:45 UTC
