### ISSUE TITLE
cephadm bootstrap prints valuable information

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#79] opened 2020-02-13 13:41 UTC
After cephadm boostrap succeeds, it prints some valuable infos:
```
INFO:cephadm:Ceph Dashboard is now available at:

             URL: https://ubuntu1804:8443/
            User: admin
        Password: wgcrj2t3ka

INFO:cephadm:You can access the Ceph CLI with:

        sudo ./cephadm shell --fsid 146d0150-4e66-11ea-a110-5254005c2d4e -c ceph.conf -k ceph.client.admin.keyring

INFO:cephadm:Bootstrap complete.
```

We should forward users the information about the dashboard password and provide a convenience wrapper for `cephadm shell`

**Comment by ricardoasmarques** [comment] 2020-09-23 20:52
Closing as a duplicate of https://github.com/ceph/ceph-salt/issues/296

**Closed as completed by ricardoasmarques** 2020-09-23 20:52 UTC
