### ISSUE TITLE
No manual entry for ceph-salt 

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#414] opened 2020-09-30 13:43 UTC
```
master:~ # ceph-salt --version
ceph-salt 15.2.12+1601288307.gf6c5fd7
master:~ # man ceph-salt
No manual entry for ceph-salt
```

**Comment by ricardoasmarques** [comment] 2020-09-30 14:13
Duplicate of https://github.com/ceph/ceph-salt/issues/279

**Closed as completed by ricardoasmarques** 2020-09-30 14:13 UTC
Labels: documentation
