### ISSUE TITLE
avoid :latest tag

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#280] opened 2020-06-29 12:43 UTC
https://github.com/SUSE/doc-ses/issues/398

If a user enters a `/containers/images/ceph` without a tag name, `:latest` will be used, which breaks upgrades to future patch releases.

**Comment by ricardoasmarques** [comment] 2020-07-01 13:45
@sebastian-philipp is https://github.com/ceph/ceph-salt/pull/282 sufficient to close this issue, or there's anything missing?

**Comment by sebastian-philipp** [comment] 2020-07-01 13:50
I mean, `:latest` is **really** bad. Everything works perfectly well without any flaws. Then. we push a new maintenance update, and suddenly you'll get a mixed-version cluster bypassing the usual upgrade procedure. Then we push a second maint-update and suddenly you have three minor versions in your cluster. And then the user wants to migrate to the first maint-update and suddenly you're downgrading your cluster partially, which is not supported.

**Comment by smithfarm** [comment] 2020-07-01 14:45
I think it's fine to tell the user to specify a version number explicitly, but it's not clear to me how the user is going to know which version number to specify. For example, if I'm a user and I want to install a new cluster with "the latest" version, how do I know which version number to specify at the end of the image path?

**Comment by sebastian-philipp** [comment] 2020-07-02 11:26
https://github.com/SUSE/doc-ses/pull/410

**Comment by asettle** [comment] 2020-07-02 11:26
> [SUSE/doc-ses#410](https://github.com/SUSE/doc-ses/pull/410)

Let me know if there's anyway I can make this clearer.

**Comment by sebastian-philipp** [comment] 2020-07-02 11:27
> > [SUSE/doc-ses#410](https://github.com/SUSE/doc-ses/pull/410)
> 
> Let me know if there's anyway I can make this clearer.

I think that's ok

**Comment by tserong** [comment] 2020-07-06 11:24
> I mean, `:latest` is **really** bad. Everything works perfectly well without any flaws. Then. we push a new maintenance update, and suddenly you'll get a mixed-version cluster bypassing the usual upgrade procedure. Then we push a second maint-update and suddenly you have three minor versions in your cluster. And then the user wants to migrate to the first maint-update and suddenly you're downgrading your cluster partially, which is not supported.

Why would you "suddenly" have a mixed version cluster just because we pushed a new maintenance update? Wouldn't that only be a potential problem at the time of deploying a new node? Or am I missing some important detail?

Why would the user want to migrate to the first maintenance update in the above example? Shouldn't they always want to upgrade to the latest maintenance update?

**Comment by asettle** [comment] 2020-07-09 12:29
@mweiss logged this issue in Bugzilla. Ensuring he is tagged to monitor the situation.

**Comment by sebastian-philipp** [comment] 2020-09-09 08:41
close`

**Comment by ricardoasmarques** [comment] 2020-09-11 10:07
Closing as a duplicate of https://github.com/ceph/ceph-salt/issues/300

**Closed as completed by ricardoasmarques** 2020-09-11 10:07 UTC
